#
#POST http://localhost:4004/productshop/helloAction
#Content-Type: application/json

#GET http://localhost:4004/productshop/MyFunction(category=2) 

#GET http://localhost:4004/productshop/Supplier?$expand=product

POST  http://localhost:4004/productshop/Product
Content-Type: application/json

{
   "name" : "iphone12",
    "stock" : 15
}